CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price REAL NOT NULL,
  currency_id VARCHAR(10) NOT NULL,
  available_quantity INT NOT NULL,
  product_condition VARCHAR(20) NOT NULL,
  free_shipping BOOLEAN NOT NULL,
  description VARCHAR(1024),
  picture_url VARCHAR(1024)
);
